breeds = [
    "Affenpinscher",
    "Afghan Hound",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Alaskan Malamute",
    "American Bulldog",
    "American Eskimo Dog",
    "American Hairless Terrier",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Anatolian Shepherd",
    "Australian Cattle Dog",
    "Australian Kelpie",
    "Australian Shepherd",
    "Australian Terrier",
    "Basenji",
    "Basset Griffon Vendeen",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Beauceron",
    "Belgian Malinois",
    "Belgian Shepherd",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Black and Tan Coonhound",
    "Black Mouth Cur",
    "Bloodhound",
    "Blue Heeler",
    "Blue Lacy/Texas Lacy",
    "Bluetick Coonhound",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Brittany",
    "Brussels Griffon",
    "Bull Terrier",
    "Bulldog",
    "Bullmastiff",
    "Cairn Terrier",
    "Canaan Dog",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Carolina Dog",
    "Catahoula Leopard Dog",
    "Cattle Dog",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Crested",
    "Chinook",
    "Chow Chow",
    "Clumber Spaniel",
    "Cockapoo",
    "Cocker Spaniel",
    "Collie",
    "Coonhound",
    "Coonhound (Unknown Type)",
    "Corgi",
    "Coton de Tulear",
    "Curly-Coated Retriever",
    "Dachshund",
    "Dalmatian",
    "Dandie Dinmont Terrier",
    "Doberman Pinscher",
    "Dogo Argentino",
    "Dogue de Bordeaux",
    "Dutch Shepherd",
    "English (Redtick) Coonhound",
    "English Bulldog",
    "English Mastiff",
    "English Pointer",
    "English Setter",
    "English Sheepdog",
    "English Shepherd",
    "English Springer Spaniel",
    "English Toy Spaniel",
    "Eskimo Spitz",
    "Feist",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "Fox Terrier (Smooth)",
    "Fox Terrier (Toy)",
    "Fox Terrier (Wirehaired)",
    "Foxhound",
    "French Bulldog",
    "French Mastiff",
    "German Pinscher",
    "German Shepherd Dog",
    "German Shorthaired Pointer",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Golden Retriever",
    "Goldendoodle",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Greyhound",
    "Harrier",
    "Havanese",
    "Hound (Unknown Type)",
    "Hovawart",
    "Husky",
    "Irish Setter",
    "Irish Terrier",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Jindo",
    "Kai Dog",
    "Keeshond",
    "King Charles Spaniel",
    "Labradoodle",
    "Labrador Retriever",
    "Lancashire Heeler",
    "Leonberger",
    "Lhasa Apso",
    "Maltese",
    "Manchester Terrier",
    "Maremma Sheepdog",
    "Mastiff",
    "Miniature Pinscher",
    "Miniature Poodle",
    "Miniature Schnauzer",
    "Mixed Breed (Large)",
    "Mixed Breed (Medium)",
    "Mixed Breed (Small)",
    "Mountain Cur",
    "Munsterlander",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwegian Elkhound",
    "Norwich Terrier",
    "Nova Scotia Duck-Tolling Retriever",
    "Old English Sheepdog",
    "Otterhound",
    "Papillon",
    "Parson Russell Terrier",
    "Patterdale Terrier (Fell Terrier)",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Petit Basset Griffon Vendeen",
    "Pharaoh Hound",
    "Pit Bull Terrier",
    "Plott Hound",
    "Podengo Portugueso",
    "Pointer",
    "Pomeranian",
    "Poodle (Miniature)",
    "Poodle (Standard)",
    "Poodle (Toy or Tea Cup)",
    "Portuguese Water Dog",
    "Presa Canario",
    "Pug",
    "Rat Terrier",
    "Redbone Coonhound",
    "Redtick Coonhound",
    "Retriever (Unknown Type)",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saluki",
    "Samoyed",
    "Schipperke",
    "Schnauzer (Giant)",
    "Schnauzer (Miniature)",
    "Schnauzer (Standard)",
    "Scottie Scottish Terrier",
    "Sealyham Terrier",
    "Setter (Unknown Type)",
    "Shar Pei",
    "Sheltie Shetland Sheepdog",
    "Shepherd (Unknown Type)",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Silky Terrier",
    "Skye Terrier",
    "Smooth Fox Terrier",
    "Spaniel (Unknown Type)",
    "Spitz (Unknown Type Large)",
    "Spitz (Unknown Type Medium)",
    "Spitz (Unknown Type Small)",
    "Springer Spaniel",
    "St. Bernard",
    "Staffordshire Bull Terrier",
    "Standard Poodle",
    "Standard Schnauzer",
    "Swedish Vallhund",
    "Terrier (Unknown Type Medium)",
    "Terrier (Unknown Type Small)",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Toy Fox Terrier",
    "Toy Poodle",
    "Treeing Walker Coonhound",
    "Vizsla",
    "Weimaraner",
    "Welsh Corgi",
    "Welsh Springer Spaniel",
    "Westie West Highland White Terrier",
    "Wheaten Terrier",
    "Whippet",
    "Wirehaired Fox Terrier",
    "Wirehaired Pointing Griffon",
    "Xoloitzcuintle/Mexican Hairless",
    "Yorkie Yorkshire Terrier"
]

def getBreeds():
    return breeds